[package]
name = "regex-example"
version = "0.1.0"
authors = ["cklellie <christopherjkelly@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.1.41"
